name: Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      # JSON array of changed filters
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Paths Filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            github-cli-persistence:
              - 'src/github-cli-persistence/**'
              - 'test/github-cli-persistence/**'
              - .github/workflows/test.yaml
            terraform-cli-persistence:
              - 'src/terraform-cli-persistence/**'
              - 'test/terraform-cli-persistence/**'
              - .github/workflows/test.yaml
            aws-cli-persistence:
              - 'src/aws-cli-persistence/**'
              - 'test/aws-cli-persistence/**'
              - .github/workflows/test.yaml
            lamdera:
              - 'src/lamdera/**'
              - 'test/lamdera/**'
              - .github/workflows/test.yaml

  test-autogenerated:
    needs: detect-changes
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJson(needs.detect-changes.outputs.changes) }}
        baseImage:
          - debian:latest
          - ubuntu:latest
          - mcr.microsoft.com/devcontainers/base:ubuntu
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-scenarios:
    needs: detect-changes
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJson(needs.detect-changes.outputs.changes) }}
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
